/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as OfficialRouteImport } from './routes/official'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppSafetyRouteImport } from './routes/app.safety'
import { Route as AppVerifyRouteImport } from './routes/app.verify'
import { Route as AppSafetyIndexRouteImport } from './routes/app.safety.index'
import { Route as AppSafetyPoliceRouteImport } from './routes/app.safety.police'
import { Route as AppSafetySosRouteImport } from './routes/app.safety.sos'
import { Route as AppVerifyIndexRouteImport } from './routes/app.verify.index'
import { Route as AppVerifyScanRouteImport } from './routes/app.verify.scan'
import { Route as AppSafetyPoliceIdRouteImport } from './routes/app.safety.police.$id'
import { Route as AppVerifyReceiptIdRouteImport } from './routes/app.verify.receipt.$id'
import { Route as AppVerifySessionIdRouteImport } from './routes/app.verify.session.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficialRoute = OfficialRouteImport.update({
  id: '/official',
  path: '/official',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppSafetyRoute = AppSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => AppRoute,
} as any)
const AppVerifyRoute = AppVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AppRoute,
} as any)
const AppSafetyIndexRoute = AppSafetyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSafetyRoute,
} as any)
const AppSafetyPoliceRoute = AppSafetyPoliceRouteImport.update({
  id: '/police',
  path: '/police',
  getParentRoute: () => AppSafetyRoute,
} as any)
const AppSafetySosRoute = AppSafetySosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => AppSafetyRoute,
} as any)
const AppVerifyIndexRoute = AppVerifyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppVerifyRoute,
} as any)
const AppVerifyScanRoute = AppVerifyScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppVerifyRoute,
} as any)
const AppSafetyPoliceIdRoute = AppSafetyPoliceIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppSafetyPoliceRoute,
} as any)
const AppVerifyReceiptIdRoute = AppVerifyReceiptIdRouteImport.update({
  id: '/receipt/$id',
  path: '/receipt/$id',
  getParentRoute: () => AppVerifyRoute,
} as any)
const AppVerifySessionIdRoute = AppVerifySessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => AppVerifyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/official': typeof OfficialRoute
  '/app/activity': typeof AppActivityRoute
  '/app/safety': typeof AppSafetyRouteWithChildren
  '/app/verify': typeof AppVerifyRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/safety/police': typeof AppSafetyPoliceRouteWithChildren
  '/app/safety/sos': typeof AppSafetySosRoute
  '/app/verify/scan': typeof AppVerifyScanRoute
  '/app/safety/': typeof AppSafetyIndexRoute
  '/app/verify/': typeof AppVerifyIndexRoute
  '/app/safety/police/$id': typeof AppSafetyPoliceIdRoute
  '/app/verify/receipt/$id': typeof AppVerifyReceiptIdRoute
  '/app/verify/session/$id': typeof AppVerifySessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/official': typeof OfficialRoute
  '/app/activity': typeof AppActivityRoute
  '/app': typeof AppIndexRoute
  '/app/safety/police': typeof AppSafetyPoliceRouteWithChildren
  '/app/safety/sos': typeof AppSafetySosRoute
  '/app/verify/scan': typeof AppVerifyScanRoute
  '/app/safety': typeof AppSafetyIndexRoute
  '/app/verify': typeof AppVerifyIndexRoute
  '/app/safety/police/$id': typeof AppSafetyPoliceIdRoute
  '/app/verify/receipt/$id': typeof AppVerifyReceiptIdRoute
  '/app/verify/session/$id': typeof AppVerifySessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/official': typeof OfficialRoute
  '/app/activity': typeof AppActivityRoute
  '/app/safety': typeof AppSafetyRouteWithChildren
  '/app/verify': typeof AppVerifyRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/safety/police': typeof AppSafetyPoliceRouteWithChildren
  '/app/safety/sos': typeof AppSafetySosRoute
  '/app/verify/scan': typeof AppVerifyScanRoute
  '/app/safety/': typeof AppSafetyIndexRoute
  '/app/verify/': typeof AppVerifyIndexRoute
  '/app/safety/police/$id': typeof AppSafetyPoliceIdRoute
  '/app/verify/receipt/$id': typeof AppVerifyReceiptIdRoute
  '/app/verify/session/$id': typeof AppVerifySessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/official'
    | '/app/activity'
    | '/app/safety'
    | '/app/verify'
    | '/app/'
    | '/app/safety/police'
    | '/app/safety/sos'
    | '/app/verify/scan'
    | '/app/safety/'
    | '/app/verify/'
    | '/app/safety/police/$id'
    | '/app/verify/receipt/$id'
    | '/app/verify/session/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/official'
    | '/app/activity'
    | '/app'
    | '/app/safety/police'
    | '/app/safety/sos'
    | '/app/verify/scan'
    | '/app/safety'
    | '/app/verify'
    | '/app/safety/police/$id'
    | '/app/verify/receipt/$id'
    | '/app/verify/session/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/official'
    | '/app/activity'
    | '/app/safety'
    | '/app/verify'
    | '/app/'
    | '/app/safety/police'
    | '/app/safety/sos'
    | '/app/verify/scan'
    | '/app/safety/'
    | '/app/verify/'
    | '/app/safety/police/$id'
    | '/app/verify/receipt/$id'
    | '/app/verify/session/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OfficialRoute: typeof OfficialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/official': {
      id: '/official'
      path: '/official'
      fullPath: '/official'
      preLoaderRoute: typeof OfficialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/safety': {
      id: '/app/safety'
      path: '/safety'
      fullPath: '/app/safety'
      preLoaderRoute: typeof AppSafetyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/verify': {
      id: '/app/verify'
      path: '/verify'
      fullPath: '/app/verify'
      preLoaderRoute: typeof AppVerifyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/safety/': {
      id: '/app/safety/'
      path: '/'
      fullPath: '/app/safety/'
      preLoaderRoute: typeof AppSafetyIndexRouteImport
      parentRoute: typeof AppSafetyRoute
    }
    '/app/safety/police': {
      id: '/app/safety/police'
      path: '/police'
      fullPath: '/app/safety/police'
      preLoaderRoute: typeof AppSafetyPoliceRouteImport
      parentRoute: typeof AppSafetyRoute
    }
    '/app/safety/sos': {
      id: '/app/safety/sos'
      path: '/sos'
      fullPath: '/app/safety/sos'
      preLoaderRoute: typeof AppSafetySosRouteImport
      parentRoute: typeof AppSafetyRoute
    }
    '/app/verify/': {
      id: '/app/verify/'
      path: '/'
      fullPath: '/app/verify/'
      preLoaderRoute: typeof AppVerifyIndexRouteImport
      parentRoute: typeof AppVerifyRoute
    }
    '/app/verify/scan': {
      id: '/app/verify/scan'
      path: '/scan'
      fullPath: '/app/verify/scan'
      preLoaderRoute: typeof AppVerifyScanRouteImport
      parentRoute: typeof AppVerifyRoute
    }
    '/app/safety/police/$id': {
      id: '/app/safety/police/$id'
      path: '/$id'
      fullPath: '/app/safety/police/$id'
      preLoaderRoute: typeof AppSafetyPoliceIdRouteImport
      parentRoute: typeof AppSafetyPoliceRoute
    }
    '/app/verify/receipt/$id': {
      id: '/app/verify/receipt/$id'
      path: '/receipt/$id'
      fullPath: '/app/verify/receipt/$id'
      preLoaderRoute: typeof AppVerifyReceiptIdRouteImport
      parentRoute: typeof AppVerifyRoute
    }
    '/app/verify/session/$id': {
      id: '/app/verify/session/$id'
      path: '/session/$id'
      fullPath: '/app/verify/session/$id'
      preLoaderRoute: typeof AppVerifySessionIdRouteImport
      parentRoute: typeof AppVerifyRoute
    }
  }
}

interface AppSafetyPoliceRouteChildren {
  AppSafetyPoliceIdRoute: typeof AppSafetyPoliceIdRoute
}

const AppSafetyPoliceRouteChildren: AppSafetyPoliceRouteChildren = {
  AppSafetyPoliceIdRoute: AppSafetyPoliceIdRoute,
}

const AppSafetyPoliceRouteWithChildren = AppSafetyPoliceRoute._addFileChildren(
  AppSafetyPoliceRouteChildren,
)

interface AppSafetyRouteChildren {
  AppSafetyPoliceRoute: typeof AppSafetyPoliceRouteWithChildren
  AppSafetySosRoute: typeof AppSafetySosRoute
  AppSafetyIndexRoute: typeof AppSafetyIndexRoute
}

const AppSafetyRouteChildren: AppSafetyRouteChildren = {
  AppSafetyPoliceRoute: AppSafetyPoliceRouteWithChildren,
  AppSafetySosRoute: AppSafetySosRoute,
  AppSafetyIndexRoute: AppSafetyIndexRoute,
}

const AppSafetyRouteWithChildren = AppSafetyRoute._addFileChildren(
  AppSafetyRouteChildren,
)

interface AppVerifyRouteChildren {
  AppVerifyScanRoute: typeof AppVerifyScanRoute
  AppVerifyIndexRoute: typeof AppVerifyIndexRoute
  AppVerifyReceiptIdRoute: typeof AppVerifyReceiptIdRoute
  AppVerifySessionIdRoute: typeof AppVerifySessionIdRoute
}

const AppVerifyRouteChildren: AppVerifyRouteChildren = {
  AppVerifyScanRoute: AppVerifyScanRoute,
  AppVerifyIndexRoute: AppVerifyIndexRoute,
  AppVerifyReceiptIdRoute: AppVerifyReceiptIdRoute,
  AppVerifySessionIdRoute: AppVerifySessionIdRoute,
}

const AppVerifyRouteWithChildren = AppVerifyRoute._addFileChildren(
  AppVerifyRouteChildren,
)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppSafetyRoute: typeof AppSafetyRouteWithChildren
  AppVerifyRoute: typeof AppVerifyRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppSafetyRoute: AppSafetyRouteWithChildren,
  AppVerifyRoute: AppVerifyRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OfficialRoute: OfficialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
