/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as OfficialRouteImport } from './routes/official'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppSafetyRouteImport } from './routes/app.safety'
import { Route as AppVerifyRouteImport } from './routes/app.verify'
import { Route as AppVerifyIndexRouteImport } from './routes/app.verify.index'
import { Route as AppVerifyScanRouteImport } from './routes/app.verify.scan'
import { Route as AppVerifySessionRouteImport } from './routes/app.verify.session.$id'
import { Route as AppVerifyReceiptRouteImport } from './routes/app.verify.receipt.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficialRoute = OfficialRouteImport.update({
  id: '/official',
  path: '/official',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppSafetyRoute = AppSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => AppRoute,
} as any)
const AppVerifyRoute = AppVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AppRoute,
} as any)
const AppVerifyIndexRoute = AppVerifyIndexRouteImport.update({
  id: '/app/verify/',
  path: '/',
  getParentRoute: () => AppVerifyRoute,
} as any)
const AppVerifyScanRoute = AppVerifyScanRouteImport.update({
  id: '/app/verify/scan',
  path: '/scan',
  getParentRoute: () => AppVerifyRoute,
} as any)
const AppVerifySessionRoute = AppVerifySessionRouteImport.update({
  id: '/app/verify/session/$id',
  path: '/session/$id',
  getParentRoute: () => AppVerifyRoute,
} as any)
const AppVerifyReceiptRoute = AppVerifyReceiptRouteImport.update({
  id: '/app/verify/receipt/$id',
  path: '/receipt/$id',
  getParentRoute: () => AppVerifyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/official': typeof OfficialRoute
  '/app/activity': typeof AppActivityRoute
  '/app/safety': typeof AppSafetyRoute
  '/app/verify': typeof AppVerifyRoute
  '/app/verify/': typeof AppVerifyIndexRoute
  '/app/verify/scan': typeof AppVerifyScanRoute
  '/app/verify/session/$id': typeof AppVerifySessionRoute
  '/app/verify/receipt/$id': typeof AppVerifyReceiptRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/official': typeof OfficialRoute
  '/app/activity': typeof AppActivityRoute
  '/app/safety': typeof AppSafetyRoute
  '/app/verify': typeof AppVerifyRoute
  '/app/verify/': typeof AppVerifyIndexRoute
  '/app/verify/scan': typeof AppVerifyScanRoute
  '/app/verify/session/$id': typeof AppVerifySessionRoute
  '/app/verify/receipt/$id': typeof AppVerifyReceiptRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/official': typeof OfficialRoute
  '/app/activity': typeof AppActivityRoute
  '/app/safety': typeof AppSafetyRoute
  '/app/verify': typeof AppVerifyRoute
  '/app/verify/': typeof AppVerifyIndexRoute
  '/app/verify/scan': typeof AppVerifyScanRoute
  '/app/verify/session/$id': typeof AppVerifySessionRoute
  '/app/verify/receipt/$id': typeof AppVerifyReceiptRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/official'
    | '/app/activity'
    | '/app/safety'
    | '/app/verify'
    | '/app/verify/'
    | '/app/verify/scan'
    | '/app/verify/session/$id'
    | '/app/verify/receipt/$id'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/official'
    | '/app/activity'
    | '/app/safety'
    | '/app/verify'
    | '/app/verify/'
    | '/app/verify/scan'
    | '/app/verify/session/$id'
    | '/app/verify/receipt/$id'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/official'
    | '/app/activity'
    | '/app/safety'
    | '/app/verify'
    | '/app/verify/'
    | '/app/verify/scan'
    | '/app/verify/session/$id'
    | '/app/verify/receipt/$id'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OfficialRoute: typeof OfficialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/official': {
      id: '/official'
      path: '/official'
      fullPath: '/official'
      preLoaderRoute: typeof OfficialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/safety': {
      id: '/app/safety'
      path: '/safety'
      fullPath: '/app/safety'
      preLoaderRoute: typeof AppSafetyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/verify': {
      id: '/app/verify'
      path: '/verify'
      fullPath: '/app/verify'
      preLoaderRoute: typeof AppVerifyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/verify/': {
      id: '/app/verify/'
      path: '/'
      fullPath: '/app/verify/'
      preLoaderRoute: typeof AppVerifyIndexRouteImport
      parentRoute: typeof AppVerifyRoute
    }
    '/app/verify/scan': {
      id: '/app/verify/scan'
      path: '/scan'
      fullPath: '/app/verify/scan'
      preLoaderRoute: typeof AppVerifyScanRouteImport
      parentRoute: typeof AppVerifyRoute
    }
    '/app/verify/session/$id': {
      id: '/app/verify/session/$id'
      path: '/session/$id'
      fullPath: '/app/verify/session/$id'
      preLoaderRoute: typeof AppVerifySessionRouteImport
      parentRoute: typeof AppVerifyRoute
    }
    '/app/verify/receipt/$id': {
      id: '/app/verify/receipt/$id'
      path: '/receipt/$id'
      fullPath: '/app/verify/receipt/$id'
      preLoaderRoute: typeof AppVerifyReceiptRouteImport
      parentRoute: typeof AppVerifyRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppSafetyRoute: typeof AppSafetyRoute
  AppVerifyRoute: typeof AppVerifyRoute
  AppIndexRoute: typeof AppIndexRoute
}

interface AppVerifyRouteChildren {
  AppVerifyIndexRoute: typeof AppVerifyIndexRoute
  AppVerifyScanRoute: typeof AppVerifyScanRoute
  AppVerifySessionRoute: typeof AppVerifySessionRoute
  AppVerifyReceiptRoute: typeof AppVerifyReceiptRoute
}

const AppVerifyRouteChildren: AppVerifyRouteChildren = {
  AppVerifyIndexRoute,
  AppVerifyScanRoute,
  AppVerifySessionRoute,
  AppVerifyReceiptRoute,
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppSafetyRoute: AppSafetyRoute,
  AppVerifyRoute: AppVerifyRoute._addFileChildren(AppVerifyRouteChildren),
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OfficialRoute: OfficialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
